### ISSUE TITLE
[Windows] test failing

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-pipe#5]
After merging https://github.com/elasticsearch/logstash/pull/2507 we have this new issue.
```
Failures:
  1) inputs/pipe echo inputs
     Failure/Error: block.call(pipeline, queue)
     Insist::Failure:
       Expected "?", but got "?"
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:58:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:113:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:171:in `run'

```

related to unicode on windows.

**Comment by ph** [comment]
https://github.com/elasticsearch/logstash/issues/2487

**Comment by ph** [comment]
updated ticket.

**Comment by ph** [comment]
we don't support pipe on windows, fixed in https://github.com/logstash-plugins/logstash-input-pipe/pull/4

**Comment by jsvd** [comment]
#4 has been merged
